### ISSUE TITLE
try up from docker-compose issue

### ISSUE THREAD

**Issue by dogonovm** [stringer-rss/stringer#1096]
Hi, 

I try run project use images from docker hub. 

docker-compose.yml
```
version: '3.5'

services:
  stringer-postgres:
    image: postgres:9.5-alpine
    restart: always
    hostname: stringer-postgres
    container_name: stringer-postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment: 
       POSTGRES_PASSWORD: ********
       POSTGRES_DB: stringer
  stringer:
    image: stringerrss/stringer:latest
    restart: always
    ports:
      - 8000:8080
    environment:
       PORT: 8080
       DATABASE_URL: postgres://postgres:*********@stringer-postgres/stringer
       SECRET_KEY_BASE: *********
       ENCRYPTION_PRIMARY_KEY: *********
       ENCRYPTION_DETERMINISTIC_KEY: *********
       ENCRYPTION_KEY_DERIVATION_SALT: *********
       FETCH_FEEDS_CRON: "*/5 * * * *"
       CLEANUP_CRON: "0 0 * * *"
```

log: 
```
stringer_1           | 2023-09-02 19:19:21,774 DEBG 'puma' stdout output:
stringer_1           | Warning: You specified code to run in a `before_fork` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `before_fork` block did not run
stringer_1           | 
stringer_1           | 2023-09-02 19:19:21,777 DEBG 'puma' stdout output:
stringer_1           | Warning: You specified code to run in a `on_worker_boot` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `on_worker_boot` block did not run
stringer_1           | Warning: You specified code to run in a `on_worker_shutdown` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `on_worker_shutdown` block did not run
stringer_1           | [11] Puma starting in cluster mode...
stringer_1           | [11] * Puma version: 6.3.1 (ruby 3.2.2-p53) ("Mugi No Toki Itaru")
stringer_1           | [11] *  Min threads: 2
stringer_1           | [11] *  Max threads: 2
stringer_1           | [11] *  Environment: production
stringer_1           | [11] *   Master PID: 11
stringer_1           | [11] *      Workers: 2
stringer_1           | [11] *     Restarts: (✔) hot (✖) phased
stringer_1           | [11] * Preloading application
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,560 DEBG 'puma' stdout output:
stringer_1           | [11] * Listening on http://0.0.0.0:8080
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,567 DEBG 'puma' stdout output:
stringer_1           | [11] ! WARNING: Detected 5 Thread(s) started in app boot:
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,569 DEBG 'puma' stdout output:
stringer_1           | [11] ! #<Thread:0x00007fb7f1034278@worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,571 DEBG 'puma' stdout output:
stringer_1           | [11] ! #<Thread:0x00007fb7f10324f0@io-worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep_forever> - <internal:thread_sync>:18:in `pop'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,573 DEBG 'puma' stdout output:
stringer_1           | [11] ! #<Thread:0x00007fb7f10578e0@GoodJob::Scheduler(queues=* max_threads=5)-worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,576 DEBG 'puma' stdout output:
stringer_1           | [11] ! #<Thread:0x00007fb7f0f0e470@GoodJob::Scheduler(queues=* max_threads=5)-thread-2 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep_forever> - /usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/model_schema.rb:563:in `synchronize'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,577 DEBG 'puma' stdout output:
stringer_1           | [11] ! #<Thread:0x00007fb7f0f0d7c8@worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:53:in `sleep'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,578 DEBG 'puma' stdout output:
stringer_1           | [11] Use Ctrl-C to stop
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,579 DEBG 'puma' stdout output:
stringer_1           | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,647 DEBG 'puma' stdout output:
stringer_1           | /usr/local/bundle/gems/puma-6.3.1/lib/puma/launcher.rb:312:in `write': No such file or directory @ rb_sysopen - tmp/pids/server.pid (Errno::ENOENT)
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/launcher.rb:312:in `write_pid'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/launcher.rb:121:in `write_state'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/cluster.rb:408:in `run'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/launcher.rb:194:in `run'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/cli.rb:75:in `run'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/bin/puma:10:in `<top (required)>'
stringer_1           |  from /usr/local/bundle/bin/puma:25:in `load'
stringer_1           |  from /usr/local/bundle/bin/puma:25:in `<top (required)>'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
stringer_1           |  from /usr/local/bundle/bin/bundle:25:in `load'
stringer_1           |  from /usr/local/bundle/bin/bundle:25:in `<main>'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:24,671 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 139680140741584 for <Subprocess at 139680140382224 with name puma in state RUNNING> (stdout)>
stringer_1           | 2023-09-02 19:19:25,673 WARN exited: puma (exit status 1; not expected)
stringer_1           | 2023-09-02 19:19:25,674 DEBG received SIGCHLD indicating a child quit
stringer_1           | 2023-09-02 19:19:26,682 INFO spawned: 'puma' with pid 26
stringer_1           | 2023-09-02 19:19:27,683 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stringer_1           | 2023-09-02 19:19:29,589 DEBG 'puma' stdout output:
stringer_1           | Warning: You specified code to run in a `before_fork` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `before_fork` block did not run
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,590 DEBG 'puma' stdout output:
stringer_1           | Warning: You specified code to run in a `on_worker_boot` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `on_worker_boot` block did not run
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,590 DEBG 'puma' stdout output:
stringer_1           | Warning: You specified code to run in a `on_worker_shutdown` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `on_worker_shutdown` block did not run
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,592 DEBG 'puma' stdout output:
stringer_1           | [26] Puma starting in cluster mode...
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,593 DEBG 'puma' stdout output:
stringer_1           | [26] * Puma version: 6.3.1 (ruby 3.2.2-p53) ("Mugi No Toki Itaru")
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,594 DEBG 'puma' stdout output:
stringer_1           | [26] *  Min threads: 2
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,594 DEBG 'puma' stdout output:
stringer_1           | [26] *  Max threads: 2
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,595 DEBG 'puma' stdout output:
stringer_1           | [26] *  Environment: production
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,595 DEBG 'puma' stdout output:
stringer_1           | [26] *   Master PID: 26
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,596 DEBG 'puma' stdout output:
stringer_1           | [26] *      Workers: 2
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,597 DEBG 'puma' stdout output:
stringer_1           | [26] *     Restarts: (✔) hot (✖) phased
stringer_1           | 
stringer_1           | 2023-09-02 19:19:29,597 DEBG 'puma' stdout output:
stringer_1           | [26] * Preloading application
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,829 DEBG 'puma' stdout output:
stringer_1           | [26] * Listening on http://0.0.0.0:8080
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,831 DEBG 'puma' stdout output:
stringer_1           | [26] ! WARNING: Detected 5 Thread(s) started in app boot:
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,832 DEBG 'puma' stdout output:
stringer_1           | [26] ! #<Thread:0x00007f8886d7d258@worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,835 DEBG 'puma' stdout output:
stringer_1           | [26] ! #<Thread:0x00007f8886d78460@io-worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep_forever> - <internal:thread_sync>:18:in `pop'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,836 DEBG 'puma' stdout output:
stringer_1           | [26] ! #<Thread:0x00007f8886d8bc68@GoodJob::Scheduler(queues=* max_threads=5)-worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep_forever> - /usr/local/bundle/gems/activesupport-7.0.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `enter'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,837 DEBG 'puma' stdout output:
stringer_1           | [26] ! #<Thread:0x00007f8886dacaa8@GoodJob::Scheduler(queues=* max_threads=5)-thread-2 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/pg-1.5.3/lib/pg/connection.rb:703:in `set_default_encoding'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,838 DEBG 'puma' stdout output:
stringer_1           | [26] ! #<Thread:0x00007f8886dab388@worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:53:in `sleep'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,839 DEBG 'puma' stdout output:
stringer_1           | [26] Use Ctrl-C to stop
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,839 DEBG 'puma' stdout output:
stringer_1           | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,879 DEBG 'puma' stdout output:
stringer_1           | /usr/local/bundle/gems/puma-6.3.1/lib/puma/launcher.rb:312:in `write': No such file or directory @ rb_sysopen - tmp/pids/server.pid (Errno::ENOENT)
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/launcher.rb:312:in `write_pid'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/launcher.rb:121:in `write_state'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/cluster.rb:408:in `run'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/launcher.rb:194:in `run'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/lib/puma/cli.rb:75:in `run'
stringer_1           |  from /usr/local/bundle/gems/puma-6.3.1/bin/puma:10:in `<top (required)>'
stringer_1           |  from /usr/local/bundle/bin/puma:25:in `load'
stringer_1           |  from /usr/local/bundle/bin/puma:25:in `<top (required)>'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
stringer_1           |  from /usr/local/bundle/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
stringer_1           |  from /usr/local/bundle/bin/bundle:25:in `load'
stringer_1           |  from /usr/local/bundle/bin/bundle:25:in `<main>'
stringer_1           | 
stringer_1           | 2023-09-02 19:19:31,896 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 139680140803472 for <Subprocess at 139680140382224 with name puma in state RUNNING> (stdout)>
stringer_1           | 2023-09-02 19:19:32,898 WARN exited: puma (exit status 1; not expected)
stringer_1           | 2023-09-02 19:19:32,899 DEBG received SIGCHLD indicating a child quit
stringer_1           | 2023-09-02 19:19:33,902 INFO spawned: 'puma' with pid 37
stringer_1           | 2023-09-02 19:19:34,905 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stringer_1           | 2023-09-02 19:19:36,611 DEBG 'puma' stdout output:
stringer_1           | Warning: You specified code to run in a `before_fork` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `before_fork` block did not run
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,612 DEBG 'puma' stdout output:
stringer_1           | Warning: You specified code to run in a `on_worker_boot` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `on_worker_boot` block did not run
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,613 DEBG 'puma' stdout output:
stringer_1           | Warning: You specified code to run in a `on_worker_shutdown` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `on_worker_shutdown` block did not run
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,614 DEBG 'puma' stdout output:
stringer_1           | [37] Puma starting in cluster mode...
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,615 DEBG 'puma' stdout output:
stringer_1           | [37] * Puma version: 6.3.1 (ruby 3.2.2-p53) ("Mugi No Toki Itaru")
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,615 DEBG 'puma' stdout output:
stringer_1           | [37] *  Min threads: 2
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,616 DEBG 'puma' stdout output:
stringer_1           | [37] *  Max threads: 2
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,617 DEBG 'puma' stdout output:
stringer_1           | [37] *  Environment: production
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,617 DEBG 'puma' stdout output:
stringer_1           | [37] *   Master PID: 37
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,618 DEBG 'puma' stdout output:
stringer_1           | [37] *      Workers: 2
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,618 DEBG 'puma' stdout output:
stringer_1           | [37] *     Restarts: (✔) hot (✖) phased
stringer_1           | 
stringer_1           | 2023-09-02 19:19:36,619 DEBG 'puma' stdout output:
stringer_1           | [37] * Preloading application
stringer_1           | 
stringer_1           | 2023-09-02 19:19:38,822 DEBG 'puma' stdout output:
stringer_1           | [37] * Listening on http://0.0.0.0:8080
stringer_1           | 
stringer_1           | 2023-09-02 19:19:38,838 DEBG 'puma' stdout output:
stringer_1           | [37] ! WARNING: Detected 5 Thread(s) started in app boot:
stringer_1           | [37] ! #<Thread:0x00007faacc4a0140@worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
stringer_1           | [37] ! #<Thread:0x00007faacc4ccba0@io-worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep_forever> - <internal:thread_sync>:18:in `pop'
stringer_1           | [37] ! #<Thread:0x00007faacc4c1160@GoodJob::Scheduler(queues=* max_threads=5)-worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
stringer_1           | [37] ! #<Thread:0x00007faacc37dd30@GoodJob::Scheduler(queues=* max_threads=5)-thread-2 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/pg-1.5.3/lib/pg/connection.rb:690:in `connect_poll'
stringer_1           | [37] ! #<Thread:0x00007faacc37cc50@worker-1 /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep> - /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:53:in `sleep'
stringer_1           | [37] Use Ctrl-C to stop
stringer_1           | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
stringer_1           | 
stringer_1           | 2023-09-02 19:19:38,868 DEBG 'puma' stdout output:
```

**Comment by guidopetri** [comment]
@dogonovm hi! I don't have a solution for your issue (yet), but you should probably change your postgres password, as well as the secret keys passed to stringer. I think you accidentally posted them here, which means anyone can see them - I can edit your message but it will still be in the history of the comment.

**Comment by guidopetri** [comment]
Confirming here that the issue is present on the latest build on Dockerhub. @mockdeep

**Comment by guidopetri** [comment]
I think it's related to [this line](https://github.com/stringer-rss/stringer/blob/main/config/puma.rb#L28). Maybe we have to create that directory first? [source](https://stackoverflow.com/questions/52862529/no-such-file-or-directory-rb-sysopen-tmp-pids-puma-pid)

**Comment by mockdeep** [comment]
@guidopetri we should [already have that directory](https://github.com/stringer-rss/stringer/tree/main/tmp/pids), so I wonder if it's having a hard time finding the file itself. Is it maybe executing from the wrong path?

**Comment by guidopetri** [comment]
Hmm... I'm not sure. As far as I can tell this is somehow related to the updated dependencies - nothing else seems to have materially changed in the past couple of weeks.

**Comment by dogonovm** [comment]
sounds good, I wait feedback from you! ))))

**Comment by guidopetri** [comment]
Found the issue: https://github.com/stringer-rss/stringer/blob/main/.dockerignore#L4 we specifically ignore everything in `./tmp` to be added in Docker. I think in this case it's acceptable to add that in. I wonder if some behavior changed in one of the recent dependency updates where the folder wasn't getting created by default anymore.

**Comment by guidopetri** [comment]
@dogonovm we should be all set now, but feel free to reopen the issue if this is still not working for you with the latest image!
