### ISSUE TITLE
Mark as read broken?

### ISSUE THREAD

**Issue by bitboxer** [stringer-rss/stringer#612]
This weekend I upgraded my 2 year old stringer to the latest code, sadly this broke the "marked as read" in my reeder apps somehow. Not sure what happend there. Anyone else having the same issue?

**Comment by bitboxer** [comment]
Okay, the reason is this:

```
NoMethodError - undefined method `update_attributes' for #<Story id: 328478, ....">
Did you mean?  update_attribute:
	/home/bitboxer/stringer/vendor/bundle/ruby/3.0.0/gems/activemodel-7.0.2.3/lib/active_model/attribute_methods.rb:458:in `method_missing'
	/home/bitboxer/stringer/app/commands/stories/mark_as_read.rb:10:in `mark_as_read'
	/home/bitboxer/stringer/app/fever_api/write_mark_item.rb:26:in `mark_item_as'
	/home/bitboxer/stringer/app/fever_api/write_mark_item.rb:16:in `call'
```

In the tests this method is mocked out and makes test still green. Sadly this method was removed in ActiveRecord 6.1:

> Remove deprecated ActiveRecord::Base#update_attributes and  ActiveRecord::Base#update_attributes!.

See: https://guides.rubyonrails.org/v6.1/6_1_release_notes.html
